---
title: "Housing Review"
author: "Zachary Palmore"
date: "10/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


## Zillow Data



```{r}

housing <- read.csv("https://raw.githubusercontent.com/palmorezm/misc/master/Housing/county_zhvi.csv")
head(housing, 8)
```


```{r}
library(ggplot2)
ggplot(housing, aes(x = StateName, y = 2020-09-30)) + 
  geom_col(aes(fill = StateName)) + 
  coord_flip() + 
  theme(legend.position = "none")
```



```{r}
library(dplyr)
# subset.data.frame(housing, 
#                  select =  c("StateName", "State", "2004-09-30", "2004-06-30", "2004-07-31"))

selection <- housing %>%
  dplyr::select(c("StateName", "State", "X2004.09.30", "X2004.06.30", "X2004.07.31", "X1996.01.31","X2019.07.31")) %>%
  group_by(State) %>% 
  arrange(desc(State))
head(selection)
```


```{r}
selection[is.na(selection)] <- 0
sum(is.na(selection))
plot(selection)
```



```{r}
hist(selection$X2004.09.30, ylim = c(0,2500), col = "pink")
hist(selection$X2004.06.30, ylim = c(0,2500), col = "light blue")
hist(selection$X2004.07.31, ylim = c(0,2500), col = "tan")
hist(selection$X2019.07.31, ylim = c(0,2500), col = "light yellow")
hist(selection$X1996.01.31, ylim = c(0,2500), col = "light grey")
```



