---
title: "RNOAA"
author: "Zachary Palmore"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## BLS API


```{r}
library(devtools)
install_github("mikeasilva/blsAPI")
```


```{r}
help(blsAPI , package = "blsAPI")
```


## How to get Data from NCDC


```{r}
library(devtools)
install.packages("rnoaa")
```


```{r}
token <- "OdFHUZoLTPJDspzZNixzfoEhgvFBUTHU" 
```



```{r}
library(rnoaa)
stations <- ncdc_stations(
  datasetid='GHCND', 
  locationid='FIPS:39113',
  token = token)
data <- ncdc_datasets(datasetid = 'GHCND', 
                      locationid = 'FIPS:US',
                      token = token)
data
```



```{r}
help(package = "rnoaa")
help('datasetid', package = "rnoaa")
??datasetid
```


```{r}
datasets <- ncdc_datasets(token = token)
data_categories <- ncdc_datacats(token = token)
datasets$data
```


```{r}
ncdc_2020 <- ncdc(datasetid = "GHCND", 
     token = token,
     startdate = '2020-01-01',
     enddate = '2020-01-04',
     locationid = 'FIPS:36061')
ncdc_2020$data

```




## How to get Data from BEA 


```{r}
install.packages(c("httr","devtools"))
```


```{r}
library(httr)
library(devtools)
```



```{r}
set_config( config( ssl_verifypeer = 0L )) 
install_github('us-bea/bea.R') 

```


```{r}
library(beaR)
```

```{r}
httr::set_config( config( ssl_verifypeer = 0L ))           #zero L
devtools::install_github('us-bea/bea.R')
```

```{r}

```


