---
title: "Untitled"
author: "Zachary Palmore"
date: "8/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 


```{r}
library(dplyr)
library(maps)
data("county.fips")
df_pop_county <- data.frame(region=county.fips$fips)
df_pop_county$value <- county.fips$fips
y <- df_pop_county$value
df_pop_county$color <- gray(y / max(y))

counties <- county.fips %>% 
  left_join(df_pop_county, by = c('fips' = 'region'))
map("county", fill = TRUE, col = counties$color)
```


```{r}
# rpp[9:nrow(rpp),1:15]
county.fips.rpp <- rpp[9:nrow(rpp),1:15]
df_pop_county.rpp <- data.frame(region=county.fips.rpp$GeoFips)
df_pop_county.rpp$value <- county.fips.rpp$`2019`
map("county", fill = TRUE, col = df_pop_county.rpp$value)
```


```{r}
library(plotrix)
df_pop_county.rpp$col <- color.scale(df_pop_county.rpp$value)
map("county", fill = TRUE, col = df_pop_county.rpp$col)
```

```{r}
df_pop_county.rpp$col <- color.scale(df_pop_county.rpp$value, alpha = 0.5, color.spec = "hsv")
map("county", fill = TRUE, col = df_pop_county.rpp$col)
```


```{r}
library(ggplot2)
df_pop_county.rpp$scale[1:1541,] <- scale_fill_gradient(df_pop_county.rpp$value)
map("county", fill = TRUE, col = df_pop_county.rpp$col)
df_pop_county.rpp$vec <- scale(df_pop_county.rpp$value, center = F, scale = T)
df.vec <- df_pop_county.rpp$vec
df_pop_county.rpp %>%
  ggplot(aes(df_pop_county.rpp$value)) + geom_point() +
  scale_color_gradient(value, low = "blue", high = "orange")
df_pop_county.rpp %>%
  ggplot(aes(region, value)) +
  geom_point(aes(color = col)) + 
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x = element_blank()) 
```


```{r}
df_pop_county.rpp %>%
  ggplot(aes(region, value)) +
  geom_point(aes(color = col)) + 
  theme(legend.position = "none",
        axis.text.x = element_blank(), 
        axis.title.x = element_blank()) + 
  geom_text(label = rownames(df_pop_county.rpp))
```


```{r}
# Requires tidy mipd data
library(plotrix)
library(maps)
data("county.fips")
df_pop_county <- data.frame(region=county.fips$fips)
df_pop_county$value <- county.fips$fips
y <- df_pop_county$value
df_pop_county$color <- gray(y / max(y))

counties <- county.fips %>% 
  left_join(df_pop_county, by = c('fips' = 'region'))
map("county", fill = TRUE, col = counties$color)

# Visualize as histogram
mipd <- mipd[-1,]
map("county", fill = TRUE, col = )
color.scale(sel)
sel <- mipd %>% 
  filter(key == 2009) 
sel$value <- as.numeric(sel$value)
sel$col <- color.scale(sel$value)
map("county", fill = T, col = sel$col)
# Visuals
theme_set(theme_bw())
ggplot(sel, aes(value)) + 
  geom_histogram(aes(fill=col)) + 
  theme(legend.position = "none")
ggplot(sel, aes(GeoName)) + 
  geom_point(aes(y = value, fill=col)) + 
  theme(legend.position = "none", 
        axis.text.y = element_blank()) + 
  coord_flip()
ggplot(sel, aes(value)) + geom_boxplot() + geom_an
```



