---
title: "Bell Pepper Report"
author: "Zachary Palmore"
date: "1/19/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Bell Pepper Experiment




```{r pkgs}
library(tidyverse)
library(readr)
library(reshape2)
theme_set(theme_bw())
```



___


```{r source}
bellpeps <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRVUsZrUEFrV0_2OQSCIn_JHCgs-ylPlFyowhr63XTCyAebIpVp7Dzq4Os_ARfm0yeEsrkenL_he4K4/pub?gid=0&single=true&output=csv", header = TRUE, sep = ",")
```


___


```{r prep}
bellpeps <- bellpeps[,1:8]
bellpeps[,3:6] <- lapply(bellpeps[,3:6], as.numeric)
bellpeps$Date <- as.Date(bellpeps$Date, format = "%m/%d/%Y")
 
# Bell peppers that are large enough to measure: 
bps.5 <- na.exclude(bellpeps)

# Bell peppers less than 0.5cm recorded as 0: 
bellpeps$PlantWidth <- replace_na(bellpeps$PlantWidth, 0)
bellpeps$PlantHeight <- replace_na(bellpeps$PlantHeight, 0)
```


___


```{r analysis}
summary(bps.5)
```


___


```{r visualize}
ggplot(bps.5, aes(Day, PlantWidth)) + geom_line(aes(fill = PlantID, color = PlantID)) + geom_point(aes(fill = PlantID, color = PlantID)) 
```





```{r}
ggplot(bps.5, aes(Day, PlantHeight)) + geom_line(aes(fill = PlantID, color = PlantID)) + geom_point(aes(fill = PlantID, color = PlantID))
```



```{r}
ggplot(bps.5, aes(Day, fill = "")) + geom_line(aes(y = PlantHeight, color = "Height", fill = PlantID)) + geom_point(aes(y = PlantHeight)) + geom_line(aes(y = PlantWidth, color = "Width", fill = PlantID)) + geom_point(aes(y = PlantWidth)) 
```



```{r}
ggplot(bps.5, aes(Day, PlantHeight)) + geom_col(aes(fill = PlantID))
```



```{r}
ggplot(bps.5, aes(Date, PlantHeight)) + 
  geom_line(aes(y = PlantWidth, color = PlantID)) + geom_point(aes(color = PlantID)) +
  geom_line(aes(color = PlantID)) + geom_point(aes(color = PlantID))
```




```{r}
bps.5 %>% 
  mutate(PlantSize = PlantWidth + PlantHeight) %>% 
  ggplot() + geom_line(aes(Day, PlantSize, color = PlantID)) + geom_point(aes(Day, PlantSize, color = PlantID))
```


```{r}
bellpeps %>% 
  melt(id = "PlantID", measure = c("PlantHeight", "PlantWidth")) %>% 
  ggplot(aes(reorder(PlantID, -value), value)) + geom_col(aes(fill = PlantID))
```





