---
title: "Outline"
author: "Team DAREZ"
date: "10/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 


```{r}
library(readxl)
Unis <- read_excel("ResearchClassification_DoctoralUniversities.xlsx")
Unis
```



```{r}
library(tidyverse)
```



```{r}
ggplot(Unis, aes(State, Rank)) + geom_col() + coord_flip()
```


```{r}
Unis %>%
  filter(Rank == "R1") %>% 
  group_by(State) %>%
  summarise(counts = sum(table(Rank)))
```


```{r}
Unis %>%
  group_by(State) %>%
  summarise(counts = sum(table(Rank))) %>%
  top_n(10) %>% 
  arrange(desc(counts)) %>% 
  ggplot(aes(State, counts, fill = State)) + 
  geom_col()
```


```{r}
Unis %>%
  group_by(State) %>%
  summarise(counts = sum(table(Rank))) %>% 
  top_n(5) %>% 
  ggplot(aes(counts, State, fill = State)) + geom_col()
```



```{r}
Unis2 <- Unis %>% 
  group_by(State) %>%
  mutate(total = sum(table(Rank)))
ggplot(Unis2, aes(State, total, fill = ResearchActivity)) + geom_col() + 
  theme_classic() + labs(y = "Count of Universities", x  = "State") + coord_flip()
```

```{r}
Unis2
```




```{r}
# Public University Rankings
pubrs <- Unis %>% 
  group_by(State) %>%
  filter(Control == "Public") %>%
  mutate(total = sum(table(Rank))) %>%  
  summarise(Rs = sum(table(total))) %>% 
  arrange(desc(Rs))
rmarkdown::paged_table(pubrs)
```


```{r}
# Non-Public University Rankings
npubrs <- Unis %>% 
  group_by(State) %>%
  filter(Control != "Public") %>%
  mutate(total = sum(table(Rank))) %>%  
  summarise(Rs = sum(table(total))) %>% 
  arrange(desc(Rs))
rmarkdown::paged_table(npubrs)
```



```{r}
Unis %>%
  filter(State == "DC")
```



```{r}
pubrs
```


```{r}
Unis %>% 
  group_by(State) %>% 
  summarise(Ranks = sum((table(Rank)))) %>%
  arrange(desc(Ranks)) %>%
  ggplot(aes(x = reorder(State, Ranks), y = Ranks)) + 
           geom_col(aes(alpha = 0.50, fill = State))  + 
  theme_minimal() +
  theme(legend.position = "none", 
        axis.title.y = element_blank(), 
        axis.text.x = element_text(angle = -45, vjust = 0.5, hjust=1)) +
  coord_flip() 
```


```{r}
Unis %>% 
  group_by(City) %>% 
  summarise(TotalUnis = sum(table(Rank))) %>%
  arrange(desc(TotalUnis))
```


